[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "www.stockwise.app"

[dev]
  command = "yarn run dev" # Command to start your dev server
  port = 8888 # Port that the dev server will be listening on
  publish = ".output" # Folder with the static content for _redirect file

 # Although there is also this redirect rule in "/public/_redirects", this must be here for local redirects.
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/portfolios"
  to = "/handle-login/:code/:state"
  status = 301
  query = { code = ":code", state = ":state" }


[functions]
  directory = "functions"
  included_files = ["database/client.ts"]
